// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from 'hyperswitch-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import Hyperswitch from 'hyperswitch';

export const metadata: Metadata = {
  resource: 'three_ds_decision',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/three_ds_decision/execute',
  operationId: 'Execute 3DS Decision Rule',
};

export const tool: Tool = {
  name: 'execute_three_ds_decision',
  description: '3DS Decision - Execute',
  inputSchema: {
    type: 'object',
    properties: {
      payment: {
        type: 'object',
        description: 'Represents the payment data used in the 3DS decision rule.',
        properties: {
          amount: {
            type: 'integer',
            description: 'The amount of the payment in minor units (e.g., cents for USD).',
          },
          currency: {
            $ref: '#/$defs/currency',
          },
        },
        required: ['amount', 'currency'],
      },
      routing_id: {
        type: 'string',
        description: 'The ID of the routing algorithm to be executed.',
      },
      acquirer: {
        type: 'object',
        description: 'Represents data about the acquirer used in the 3DS decision rule.',
        properties: {
          country: {
            $ref: '#/$defs/country',
          },
          fraud_rate: {
            type: 'number',
            description: 'The fraud rate associated with the acquirer.',
          },
        },
        required: ['country'],
      },
      customer_device: {
        type: 'object',
        description: "Represents data about the customer's device used in the 3DS decision rule.",
        properties: {
          device_type: {
            type: 'string',
            enum: ['mobile', 'tablet', 'desktop', 'gaming_console'],
          },
          display_size: {
            type: 'string',
            enum: [
              'size320x568',
              'size375x667',
              'size390x844',
              'size414x896',
              'size428x926',
              'size768x1024',
              'size834x1112',
              'size834x1194',
              'size1024x1366',
              'size1280x720',
              'size1366x768',
              'size1440x900',
              'size1920x1080',
              'size2560x1440',
              'size3840x2160',
              'size500x600',
              'size600x400',
              'size360x640',
              'size412x915',
              'size800x1280',
            ],
          },
          platform: {
            type: 'string',
            enum: ['web', 'android', 'ios'],
          },
        },
        required: [],
      },
      issuer: {
        type: 'object',
        description: 'Represents data about the issuer used in the 3DS decision rule.',
        properties: {
          country: {
            $ref: '#/$defs/country',
          },
          name: {
            type: 'string',
            description: 'The name of the issuer.',
          },
        },
        required: ['country'],
      },
      payment_method: {
        type: 'object',
        description: 'Represents metadata about the payment method used in the 3DS decision rule.',
        properties: {
          card_network: {
            $ref: '#/$defs/card_network',
          },
        },
        required: ['card_network'],
      },
    },
    $defs: {
      currency: {
        type: 'string',
        description:
          'The three-letter ISO 4217 currency code (e.g., "USD", "EUR") for the payment amount. This field is mandatory for creating a payment.',
        enum: [
          'AED',
          'AFN',
          'ALL',
          'AMD',
          'ANG',
          'AOA',
          'ARS',
          'AUD',
          'AWG',
          'AZN',
          'BAM',
          'BBD',
          'BDT',
          'BGN',
          'BHD',
          'BIF',
          'BMD',
          'BND',
          'BOB',
          'BRL',
          'BSD',
          'BTN',
          'BWP',
          'BYN',
          'BZD',
          'CAD',
          'CDF',
          'CHF',
          'CLF',
          'CLP',
          'CNY',
          'COP',
          'CRC',
          'CUC',
          'CUP',
          'CVE',
          'CZK',
          'DJF',
          'DKK',
          'DOP',
          'DZD',
          'EGP',
          'ERN',
          'ETB',
          'EUR',
          'FJD',
          'FKP',
          'GBP',
          'GEL',
          'GHS',
          'GIP',
          'GMD',
          'GNF',
          'GTQ',
          'GYD',
          'HKD',
          'HNL',
          'HRK',
          'HTG',
          'HUF',
          'IDR',
          'ILS',
          'INR',
          'IQD',
          'IRR',
          'ISK',
          'JMD',
          'JOD',
          'JPY',
          'KES',
          'KGS',
          'KHR',
          'KMF',
          'KPW',
          'KRW',
          'KWD',
          'KYD',
          'KZT',
          'LAK',
          'LBP',
          'LKR',
          'LRD',
          'LSL',
          'LYD',
          'MAD',
          'MDL',
          'MGA',
          'MKD',
          'MMK',
          'MNT',
          'MOP',
          'MRU',
          'MUR',
          'MVR',
          'MWK',
          'MXN',
          'MYR',
          'MZN',
          'NAD',
          'NGN',
          'NIO',
          'NOK',
          'NPR',
          'NZD',
          'OMR',
          'PAB',
          'PEN',
          'PGK',
          'PHP',
          'PKR',
          'PLN',
          'PYG',
          'QAR',
          'RON',
          'RSD',
          'RUB',
          'RWF',
          'SAR',
          'SBD',
          'SCR',
          'SDG',
          'SEK',
          'SGD',
          'SHP',
          'SLE',
          'SLL',
          'SOS',
          'SRD',
          'SSP',
          'STD',
          'STN',
          'SVC',
          'SYP',
          'SZL',
          'THB',
          'TJS',
          'TMT',
          'TND',
          'TOP',
          'TRY',
          'TTD',
          'TWD',
          'TZS',
          'UAH',
          'UGX',
          'USD',
          'UYU',
          'UZS',
          'VES',
          'VND',
          'VUV',
          'WST',
          'XAF',
          'XCD',
          'XOF',
          'XPF',
          'YER',
          'ZAR',
          'ZMW',
          'ZWL',
        ],
      },
      country: {
        type: 'string',
        enum: [
          'Afghanistan',
          'AlandIslands',
          'Albania',
          'Algeria',
          'AmericanSamoa',
          'Andorra',
          'Angola',
          'Anguilla',
          'Antarctica',
          'AntiguaAndBarbuda',
          'Argentina',
          'Armenia',
          'Aruba',
          'Australia',
          'Austria',
          'Azerbaijan',
          'Bahamas',
          'Bahrain',
          'Bangladesh',
          'Barbados',
          'Belarus',
          'Belgium',
          'Belize',
          'Benin',
          'Bermuda',
          'Bhutan',
          'BoliviaPlurinationalState',
          'BonaireSintEustatiusAndSaba',
          'BosniaAndHerzegovina',
          'Botswana',
          'BouvetIsland',
          'Brazil',
          'BritishIndianOceanTerritory',
          'BruneiDarussalam',
          'Bulgaria',
          'BurkinaFaso',
          'Burundi',
          'CaboVerde',
          'Cambodia',
          'Cameroon',
          'Canada',
          'CaymanIslands',
          'CentralAfricanRepublic',
          'Chad',
          'Chile',
          'China',
          'ChristmasIsland',
          'CocosKeelingIslands',
          'Colombia',
          'Comoros',
          'Congo',
          'CongoDemocraticRepublic',
          'CookIslands',
          'CostaRica',
          'CotedIvoire',
          'Croatia',
          'Cuba',
          'Curacao',
          'Cyprus',
          'Czechia',
          'Denmark',
          'Djibouti',
          'Dominica',
          'DominicanRepublic',
          'Ecuador',
          'Egypt',
          'ElSalvador',
          'EquatorialGuinea',
          'Eritrea',
          'Estonia',
          'Ethiopia',
          'FalklandIslandsMalvinas',
          'FaroeIslands',
          'Fiji',
          'Finland',
          'France',
          'FrenchGuiana',
          'FrenchPolynesia',
          'FrenchSouthernTerritories',
          'Gabon',
          'Gambia',
          'Georgia',
          'Germany',
          'Ghana',
          'Gibraltar',
          'Greece',
          'Greenland',
          'Grenada',
          'Guadeloupe',
          'Guam',
          'Guatemala',
          'Guernsey',
          'Guinea',
          'GuineaBissau',
          'Guyana',
          'Haiti',
          'HeardIslandAndMcDonaldIslands',
          'HolySee',
          'Honduras',
          'HongKong',
          'Hungary',
          'Iceland',
          'India',
          'Indonesia',
          'IranIslamicRepublic',
          'Iraq',
          'Ireland',
          'IsleOfMan',
          'Israel',
          'Italy',
          'Jamaica',
          'Japan',
          'Jersey',
          'Jordan',
          'Kazakhstan',
          'Kenya',
          'Kiribati',
          'KoreaDemocraticPeoplesRepublic',
          'KoreaRepublic',
          'Kuwait',
          'Kyrgyzstan',
          'LaoPeoplesDemocraticRepublic',
          'Latvia',
          'Lebanon',
          'Lesotho',
          'Liberia',
          'Libya',
          'Liechtenstein',
          'Lithuania',
          'Luxembourg',
          'Macao',
          'MacedoniaTheFormerYugoslavRepublic',
          'Madagascar',
          'Malawi',
          'Malaysia',
          'Maldives',
          'Mali',
          'Malta',
          'MarshallIslands',
          'Martinique',
          'Mauritania',
          'Mauritius',
          'Mayotte',
          'Mexico',
          'MicronesiaFederatedStates',
          'MoldovaRepublic',
          'Monaco',
          'Mongolia',
          'Montenegro',
          'Montserrat',
          'Morocco',
          'Mozambique',
          'Myanmar',
          'Namibia',
          'Nauru',
          'Nepal',
          'Netherlands',
          'NewCaledonia',
          'NewZealand',
          'Nicaragua',
          'Niger',
          'Nigeria',
          'Niue',
          'NorfolkIsland',
          'NorthernMarianaIslands',
          'Norway',
          'Oman',
          'Pakistan',
          'Palau',
          'PalestineState',
          'Panama',
          'PapuaNewGuinea',
          'Paraguay',
          'Peru',
          'Philippines',
          'Pitcairn',
          'Poland',
          'Portugal',
          'PuertoRico',
          'Qatar',
          'Reunion',
          'Romania',
          'RussianFederation',
          'Rwanda',
          'SaintBarthelemy',
          'SaintHelenaAscensionAndTristandaCunha',
          'SaintKittsAndNevis',
          'SaintLucia',
          'SaintMartinFrenchpart',
          'SaintPierreAndMiquelon',
          'SaintVincentAndTheGrenadines',
          'Samoa',
          'SanMarino',
          'SaoTomeAndPrincipe',
          'SaudiArabia',
          'Senegal',
          'Serbia',
          'Seychelles',
          'SierraLeone',
          'Singapore',
          'SintMaartenDutchpart',
          'Slovakia',
          'Slovenia',
          'SolomonIslands',
          'Somalia',
          'SouthAfrica',
          'SouthGeorgiaAndTheSouthSandwichIslands',
          'SouthSudan',
          'Spain',
          'SriLanka',
          'Sudan',
          'Suriname',
          'SvalbardAndJanMayen',
          'Swaziland',
          'Sweden',
          'Switzerland',
          'SyrianArabRepublic',
          'TaiwanProvinceOfChina',
          'Tajikistan',
          'TanzaniaUnitedRepublic',
          'Thailand',
          'TimorLeste',
          'Togo',
          'Tokelau',
          'Tonga',
          'TrinidadAndTobago',
          'Tunisia',
          'Turkey',
          'Turkmenistan',
          'TurksAndCaicosIslands',
          'Tuvalu',
          'Uganda',
          'Ukraine',
          'UnitedArabEmirates',
          'UnitedKingdomOfGreatBritainAndNorthernIreland',
          'UnitedStatesOfAmerica',
          'UnitedStatesMinorOutlyingIslands',
          'Uruguay',
          'Uzbekistan',
          'Vanuatu',
          'VenezuelaBolivarianRepublic',
          'Vietnam',
          'VirginIslandsBritish',
          'VirginIslandsUS',
          'WallisAndFutuna',
          'WesternSahara',
          'Yemen',
          'Zambia',
          'Zimbabwe',
        ],
      },
      card_network: {
        type: 'string',
        description: 'Indicates the card network.',
        enum: [
          'Visa',
          'Mastercard',
          'AmericanExpress',
          'JCB',
          'DinersClub',
          'Discover',
          'CartesBancaires',
          'UnionPay',
          'Interac',
          'RuPay',
          'Maestro',
          'Star',
          'Pulse',
          'Accel',
          'Nyce',
        ],
      },
    },
  },
};

export const handler = async (client: Hyperswitch, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  return asTextContentResult(await client.threeDSDecision.execute(body));
};

export default { metadata, tool, handler };
