// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from 'hyperswitch-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import Hyperswitch from 'hyperswitch';

export const metadata: Metadata = {
  resource: 'gsm',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/gsm/get',
  operationId: 'Retrieve Gsm Rule',
};

export const tool: Tool = {
  name: 'retrieve_gsm',
  description: 'Retrieves a Gsm Rule',
  inputSchema: {
    type: 'object',
    properties: {
      code: {
        type: 'string',
        description: 'code received from the connector',
      },
      connector: {
        $ref: '#/$defs/connector',
      },
      flow: {
        type: 'string',
        description: 'The flow in which the code and message occurred for a connector',
      },
      message: {
        type: 'string',
        description: 'message received from the connector',
      },
      sub_flow: {
        type: 'string',
        description: 'The sub_flow in which the code and message occurred  for a connector',
      },
    },
    $defs: {
      connector: {
        type: 'string',
        enum: [
          'adyenplatform',
          'stripe_billing_test',
          'phonypay',
          'fauxpay',
          'pretendpay',
          'stripe_test',
          'adyen_test',
          'checkout_test',
          'paypal_test',
          'aci',
          'adyen',
          'airwallex',
          'archipel',
          'authorizedotnet',
          'bambora',
          'bamboraapac',
          'bankofamerica',
          'barclaycard',
          'billwerk',
          'bitpay',
          'bluesnap',
          'boku',
          'braintree',
          'cashtocode',
          'chargebee',
          'checkout',
          'coinbase',
          'coingate',
          'cryptopay',
          'ctp_mastercard',
          'ctp_visa',
          'cybersource',
          'datatrans',
          'deutschebank',
          'digitalvirgo',
          'dlocal',
          'ebanx',
          'elavon',
          'facilitapay',
          'fiserv',
          'fiservemea',
          'fiuu',
          'forte',
          'getnet',
          'globalpay',
          'globepay',
          'gocardless',
          'gpayments',
          'hipay',
          'helcim',
          'hyperswitch_vault',
          'inespay',
          'iatapay',
          'itaubank',
          'jpmorgan',
          'juspaythreedsserver',
          'klarna',
          'mifinity',
          'mollie',
          'moneris',
          'multisafepay',
          'netcetera',
          'nexinets',
          'nexixpay',
          'nmi',
          'nomupay',
          'noon',
          'novalnet',
          'nuvei',
          'opennode',
          'paybox',
          'payme',
          'payone',
          'paypal',
          'paystack',
          'payu',
          'placetopay',
          'powertranz',
          'prophetpay',
          'rapyd',
          'razorpay',
          'recurly',
          'redsys',
          'shift4',
          'square',
          'stax',
          'stripe',
          'stripebilling',
          'taxjar',
          'threedsecureio',
          'tokenio',
          'trustpay',
          'tsys',
          'vgs',
          'volt',
          'wellsfargo',
          'wise',
          'worldline',
          'worldpay',
          'worldpayvantiv',
          'worldpayxml',
          'signifyd',
          'plaid',
          'riskified',
          'xendit',
          'zen',
          'zsl',
        ],
      },
    },
  },
};

export const handler = async (client: Hyperswitch, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  return asTextContentResult(await client.gsm.retrieve(body));
};

export default { metadata, tool, handler };
